// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDluDj9iU1tCGvvr5_rYkn_lY0-d-SHNX4',
    appId: '1:151681925388:web:61d795fb211e0e5e35c929',
    messagingSenderId: '151681925388',
    projectId: 'ai-child-guardian-4dc08',
    authDomain: 'ai-child-guardian-4dc08.firebaseapp.com',
    storageBucket: 'ai-child-guardian-4dc08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1JHuTDkH8e1Zsc5q4A1afcgY1wEB3QN8',
    appId: '1:151681925388:android:6a653606002801b135c929',
    messagingSenderId: '151681925388',
    projectId: 'ai-child-guardian-4dc08',
    storageBucket: 'ai-child-guardian-4dc08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiBCh6ySS9aZHiZ5v3oB55xeLnuuhK95E',
    appId: '1:151681925388:ios:4ccf341a44e9f94b35c929',
    messagingSenderId: '151681925388',
    projectId: 'ai-child-guardian-4dc08',
    storageBucket: 'ai-child-guardian-4dc08.firebasestorage.app',
    iosClientId: '151681925388-gs5ske9darghuda5uhoc5f15ujh8epga.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChildGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiBCh6ySS9aZHiZ5v3oB55xeLnuuhK95E',
    appId: '1:151681925388:ios:4ccf341a44e9f94b35c929',
    messagingSenderId: '151681925388',
    projectId: 'ai-child-guardian-4dc08',
    storageBucket: 'ai-child-guardian-4dc08.firebasestorage.app',
    iosClientId: '151681925388-gs5ske9darghuda5uhoc5f15ujh8epga.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChildGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDluDj9iU1tCGvvr5_rYkn_lY0-d-SHNX4',
    appId: '1:151681925388:web:09af45df0f893ff035c929',
    messagingSenderId: '151681925388',
    projectId: 'ai-child-guardian-4dc08',
    authDomain: 'ai-child-guardian-4dc08.firebaseapp.com',
    storageBucket: 'ai-child-guardian-4dc08.firebasestorage.app',
  );
}
